version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: twixer
